lib/raml2html.js
This was preventing use of the -r and -i options on the command line if -t was not set. With this change any of the template override options can be used individually.
=> Fixed _parsePath function to use templateParam parameter instead of global program.template variable.

lib/resource.handlebars
The selector `../uniqueId` was not returning a value, it needed to be `../../uniqueId`. Since fixing this, each modal now gets a unique id in the document, and so can toggled by the tabs. Otherwise it was not possible to click back to the Request section.
Second PR, now against develop.
=> Fix bug in resource template.

lib/template.handlebars
Added suggestion by @orkramer in issue #110. The sidebar supports scrolling on overflow.
=> Addresses issue #110: allow for sidebar overflow

lib/template.handlebars
I dislike the default gray, so I added a nice yellow background. From what I've seen online, PATCH is becoming more popular, so it should be supported.
=> Added background color for PATCH badge to CSS.

lib/raml2html.js, lib/resource.handlebars
If no request content is present when viewing a given method's details, the modal would load without a selected tab and fail to render the 'Response' tab button. This PR sets the response tab to active in that case.
I've added a handlebars helper called 'missingRequestCheckHelper' that renders content (in this case, adding the active class) if request details are missing. The naming is a little confusing, since we already have an 'emptyRequestCheckHelper' (which does the opposite - renders if method has request details). Let me know if you have a better approach!
=> Response tab is set to active when request tab isn't shown

lib/resource.nunjucks
It seems this should have read `method.headers` instead of just `headers`. Making this changes causes header items to be rendered again.
=> Fix typo preventing header items being rendered

lib/template.nunjucks
This catches the error thrown by Chrome which causes the disappearing scrollbar. Then, will modify the url back to its original one.
=> Fix issue #152

index.js
that is with regards to non-arrays vs arrays respectively. this PR will fix #202. It actually fixes two things: 
* in 0.8 the the type node was a single item not an array (that is covered [here](https://github.com/raml2html/raml2html/blob/260cef924f1b4450765d08fb6fbb870e65f77aa6/index.js#L88) now)
* if there is no root `types` declaration, the function `getRootType` should not try to find types there (covered [here](https://github.com/raml2html/raml2html/blob/260cef924f1b4450765d08fb6fbb870e65f77aa6/index.js#L97))
=> fixed issue with differences between 0.8 and 1.0 

README.md
Going to [Github Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), resulting nice syntax colored code blocks
=> Convert README.md to Github flavored Markdown

bin/raml2html
Fixes https://github.com/raml2html/raml2html/issues/212
Was:
```
[Error: Error: Api contains errors.]
```
Now:
```
{ [Error: Api contains errors.]
parserErrors: 
[ { code: 2,
message: 'Unknown node: xxx',
path: 'foo.raml',
start: 28,
end: 31,
line: 2,
column: 0,
range: [Object],
isWarning: false } ] }
```
=> fix #212: log full error to console

index.js
Checking if ramlObj.types exists before accessing its property length.
=> Fix for #232

lib/resource.nunjucks
Oops, I noticed that I wrote redundant `<li>` tag in #239,
so send another PR to fixes the problem.
I do not update the example.html for avoid conflicted with others PR.
=> Fixes #239, Remove redundant <li> tag

index.js
Fixed wrong comparison. `ramlObj.securitySchemes[index][name]` never returns `null` but `undefined`
=> Fix for issue #214

index.js, lib/item.nunjucks, lib/resource.nunjucks, lib/template.nunjucks, package.json
- old version of nunjucks depends on old version of fsevents via
chokidar, which does not work on node 6.x. See
https://github.com/strongloop/fsevents/pull/128
- nunjucks-markdown expect blocks at the same level with {% markdown %}
tag. So fix the template.
=> upgrade nunjucks and fix template

index.js
Enables custom nunjucks configurations to be used, for example:
```
const config = raml2html.getDefaultConfig('./templates/template.nunjucks');
config.setupNunjucks = function(nunjucks) {
nunjucks.addFilter('stringify', function(object) {
if(typeof object == 'string')
return object;
return JSON.stringify(object, null, 2);
})
return nunjucks;
};```
=> allow nunjucks configuration

lib/item.nunjucks
Fix item rendering so properties are displayed along with the type display name.
=> Fix template typo that stops rendering of type properties

examples/array-generic.raml, lib/resource.nunjucks
Hi 😃 
Sadly, it looks like 4.0.0-beta15 (or slightly earlier) introduced a small regression when it comes to rendering [generic arrays](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#array-type): Having something like `type: array` inside a response or request body specification resulted in a generic template render error. 
This patch should solve this by requiring also the items property being filled before iterating over it.
=> Fix generic error type

changelog.md, index.js, lib/resource.nunjucks, package.json
This fix adds query parameters to security tab in method views plus uses the displayName of securitySchemes instead of RAML document reference names.(like oauth_2_0)
=> Complement missing security scheme data

.eslintrc.js, bin/raml2html, examples/script.js, index.js, package.json
Pass all CLI options (even ones we don't know about) to themes. They can use these for theme specific things like logo paths.
Needed for https://github.com/wdullaer/raml2slate/issues/3 for example.
Reason from switching away from Commander: https://github.com/tj/commander.js/issues/609
=> Support arbitrary CLI options

README.md, examples/script.js, index.js, package.json
Use new raml2obj and new default theme. Update versions, and remove now unused code.
Closes #330.
=> Update raml2obj dependency to 5.x

bin/raml2html, index.js
Add a pretty option to skip minimizing the output during the post processing.
The use case that I have for that is that in a project that I am working on, we keep the output html file in the git repo so that we can have a reference to the api using something like rawgit.
The problem is if the api changes in anyway, the output file gets changed almost completely, and the diff in github is always not shown. So this commit can decrease the number of the changed lines, making things better.
The option is backward compatible so that things should work as expected if used the same way as before. Only if `--pretty (-p)` option is used it will not minimize the output.
=> postprocessing: add a pretty option

bin/raml2html
Hey,
this PR adds support for themes to add their own assets to the output directory of the html file. The primary reason for adding this feature is that I need a theme that bundles its assets in order to provide api documentation on local networks that don’t have access to the internet.
Themes may define a `copyAssets` method as part of their config. If they do the function will receive the target directory of the output file as their only argument and should return a Promise to indicate completion. I thought about adding some logic to handle things like strings as arguments for the `copyAssets` config option, but that is likely to fall short in terms of what people might want to do with this. The theme should know best how to handle its assets.
I wasn’t quite sure where to add the …
=> allow themes to copy assets to the output directory

bin/raml2html
As I menthioned https://github.com/raml2html/raml2html/pull/395#discussion_r216311980 if we print `error` itself we don't have enough information. We should use `trace` to get more information about problem.
Output preview:
=> Output errors with trace

index.js
Requires [raml2obj#59](https://github.com/raml2html/raml2obj/pull/59) to be merged.
Fix #394
=> Add support to RAML parser resolvers options
